import  turtle
a= turtle.Turtle()
turtle.bgcolor("lightpink")
a.shape("turtle")
def cycc(x,y,z):
   a.lt(x)
   a.fd(y)
   a.rt(90)
   a.color(z)
   a.circle(50)
   a.pencolor("black")
   a.home()
a.begin_fill()
cycc(120,50,"red")
a.end_fill()
a.begin_fill()
cycc(70,50,"green")
a.end_fill()
a.begin_fill()
cycc(80,160,"red")
a.end_fill()
a.begin_fill()
cycc(105,210,"white")
a.end_fill()

turtle.done()